### ISSUE TITLE
Gatling does not run when vagrant is started

### ISSUE THREAD

**Issue by Mrono** [smerrill/vagrant-gatling-rsync#14]
I believe this is expected, however I would prefer for this to run (in the background) when the machine is upped.  My alternative is to run a watcher script on the actual vagrant machine that handles this

**Comment by smerrill** [comment]
I would also like to do this because I completely agree that just running it on start would be great, especially for beginners.

You *can* run `vagrant gatling-rsync-auto` via a plugin like vagrant-host-shell, and maybe via vagrant-triggers, but these options are suboptimal, since the `vagrant up` never registers as finishing, so you cannot do other Vagrant commands in other windows.

I took a look at this today to see if I could get a quick proof-of-concept working and I couldn't quite get it wired up in a couple hours.

I'll try to dig in a bit more over the New Years weekend to see if this is possible (and if the same issues with `vagrant up` never finishing persist if I get it working.)

**Comment by rmahoney-bl** [comment]
@smerrill thanks so much!  This is just icing on the cake of an excellent plugin :)

**Comment by FractalizeR** [comment]
Well, that would be great. I also looking for a way to start it up automatically.

**Comment by jordanambra** [comment]
FWIW, I ended up doing something similar with a combo of vagrant-triggers and a shell script that runs with an & at the end of the command. It's not really enterprise-worthy, but I ended up with this. Save it as a file, make it executable, and run it in a block from vagrant-trigger.

```
#!/bin/bash

ACTION="$1"

if [[ "$ACTION" == "start" ]]
then
    echo "Starting file sync from host to Vagrant VM"
    vagrant rsync-auto &> /dev/null &
else
    echo "Stopping file sync with Vagrant VM"
    ps ax | grep rsync-auto | grep -v grep | awk '{ print $1 }' | xargs kill
fi
```

**Comment by smerrill** [comment]
I have a proof-of-concept working for this feature pushed to RubyGems as 0.2.0.beta.1.

I'd love some help with testing it. To do so, you will need to opt in to automatic syncing by putting the following in your Vagrantfile.

```ruby
if Vagrant.has_plugin?("vagrant-gatling-rsync")
  config.gatling.rsync_on_startup = true
end
```

Then, install the beta gem and start up an environment.

```bash
$ vagrant plugin install vagrant-gatling-rsync --plugin-version '0.2.0.beta.1'
$ vagrant up
```

It will automatically start syncing on a `vagrant up` or a `vagrant reload`.

I think that multi-box environments may not work properly if you start a specific machine, and I'm still considering if it should default to running the sync automatically; if so, I might only default it to true if there are synced folders defined.

**Comment by smerrill** [comment]
This is now in the 0.9.0 release. Please try it out.
